image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      npm install
      gp sync-done install
    command: npm run dev
  - init: gp sync-await install
    command: npx cypress run --spec 'cypress/e2e/**.cy.js'
