image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      npm install
      gp sync-done install
    command: npm run dev
  - init: npm install -g lambdatest-cypress-cli
  - init: gp sync-await install
    command: lambdatest-cypress run
